#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef ESIMMANAGERSDK_SWIFT_H
#define ESIMMANAGERSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="eSIMManagerSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreBluetooth;
@import Foundation;
@import ObjectiveC;
#endif

#import <eSIMManagerSDK/eSIMManagerSDK.h>

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="eSIMManagerSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSData;
SWIFT_PROTOCOL("_TtP14eSIMManagerSDK19DirectDataInterface_")
@protocol DirectDataInterface
@property (nonatomic, readonly) NSInteger DATA_TYPE_DEVICE;
@property (nonatomic, readonly) NSInteger DATA_TYPE_EUICC;
@property (nonatomic, readonly) NSInteger DATA_TYPE_SCARD;
@property (nonatomic, readonly) NSInteger RESULT_OK;
@property (nonatomic, readonly) NSInteger RESULT_UNKNOWN_ERROR;
@property (nonatomic, readonly) NSInteger RESULT_NEED_CONFIRMATION_CODE;
@property (nonatomic, readonly) NSInteger RESULT_NO_RESPONSE;
@property (nonatomic, readonly) NSInteger RESULT_FAILED;
@property (nonatomic, readonly) NSInteger RESULT_HTTP_ERROR;
@property (nonatomic, readonly) NSInteger RESULT_CONNECT_ERROR;
@property (nonatomic, readonly) NSInteger RESULT_SSL_ERROR;
@property (nonatomic, readonly) NSInteger RESULT_RESPONSE_ERROR;
- (void)requestWithType:(NSInteger)type data:(NSData * _Nonnull)data callback:(void (^ _Nonnull)(NSInteger, NSInteger, NSData * _Nullable))callback;
@end

@class GrpcDeviceInfo;
@class NSString;
@protocol IDeviceExtend;
SWIFT_CLASS("_TtC14eSIMManagerSDK16AbstractPbDevice")
@interface AbstractPbDevice : NSObject <DirectDataInterface>
@property (nonatomic) NSInteger DATA_TYPE_DEVICE;
@property (nonatomic) NSInteger DATA_TYPE_EUICC;
@property (nonatomic) NSInteger DATA_TYPE_SCARD;
@property (nonatomic) NSInteger DATA_TYPE_SECURITY;
@property (nonatomic) NSInteger RESULT_OK;
@property (nonatomic) NSInteger RESULT_UNKNOWN_ERROR;
@property (nonatomic) NSInteger RESULT_NEED_CONFIRMATION_CODE;
@property (nonatomic) NSInteger RESULT_NO_RESPONSE;
@property (nonatomic) NSInteger RESULT_FAILED;
@property (nonatomic) NSInteger RESULT_HTTP_ERROR;
@property (nonatomic) NSInteger RESULT_CONNECT_ERROR;
@property (nonatomic) NSInteger RESULT_SSL_ERROR;
@property (nonatomic) NSInteger RESULT_RESPONSE_ERROR;
/// 获取设备信息
- (GrpcDeviceInfo * _Nullable)getDeviceInfo SWIFT_WARN_UNUSED_RESULT;
- (void)notifyDeviceWithOperation:(NSString * _Nonnull)operation status:(NSString * _Nonnull)status message:(NSString * _Nonnull)message iccid:(NSString * _Nonnull)iccid;
/// 重启设备
- (void)resetDevice;
- (void)reopen;
- (void)close;
- (id <IDeviceExtend> _Nullable)getDeviceExtend SWIFT_WARN_UNUSED_RESULT;
- (void)requestWithType:(NSInteger)type data:(NSData * _Nonnull)data callback:(void (^ _Nonnull)(NSInteger, NSInteger, NSData * _Nullable))callback;
- (BOOL)isSCardMode SWIFT_WARN_UNUSED_RESULT;
- (void)iccTransmitApduCommandsWithApduCommands:(NSString * _Nonnull)apduCommands callback:(SWIFT_NOESCAPE void (^ _Nonnull)(NSInteger, NSData * _Nullable))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK10LPAdDevice")
@interface LPAdDevice : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic) uint16_t port;
@property (nonatomic, readonly, copy) NSString * _Nonnull host;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNetService;
SWIFT_CLASS("_TtC14eSIMManagerSDK12DNSSDService")
@interface DNSSDService : LPAdDevice
@property (nonatomic, strong) NSNetService * _Nullable service;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK12DSListResult")
@interface DSListResult : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull downloadableList;
@property (nonatomic) NSInteger resultCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DeviceConnectionState, open) {
  DeviceConnectionStateSTATE_DISCONNECTED = 0,
  DeviceConnectionStateSTATE_CONNECTING = 1,
  DeviceConnectionStateSTATE_CONNECTED = 2,
  DeviceConnectionStateSTATE_CONNECTFAIL = 3,
};

@class NSCoder;
SWIFT_CLASS("_TtC14eSIMManagerSDK21DeviceExtendException")
@interface DeviceExtendException : NSException
- (nonnull instancetype)initWithName:(NSExceptionName _Nonnull)aName reason:(NSString * _Nullable)aReason userInfo:(NSDictionary * _Nullable)aUserInfo OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK22DownloadMetadataResult")
@interface DownloadMetadataResult : NSObject
@property (nonatomic, copy) NSString * _Nonnull metadata;
@property (nonatomic) NSInteger resultCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CBPeripheral;
@class CBCentralManager;
@class CBDescriptor;
@class CBCharacteristic;
@class CBService;
SWIFT_CLASS("_TtC14eSIMManagerSDK14EuiccBleDevice")
@interface EuiccBleDevice : AbstractPbDevice <CBCentralManagerDelegate, CBPeripheralDelegate>
@property (nonatomic, strong) CBPeripheral * _Nullable currentPeripheral;
@property (nonatomic, strong) CBCentralManager * _Nullable CBManager;
@property (nonatomic, copy) void (^ _Nullable connectStateCallback)(enum DeviceConnectionState);
@property (nonatomic, copy) void (^ _Nullable isValidDeviceCallback)(BOOL);
- (nonnull instancetype)initWithBleManager:(CBCentralManager * _Nonnull)bleManager blePeripheral:(CBPeripheral * _Nonnull)blePeripheral bleDataLengthSize:(NSInteger)bleDataLengthSize OBJC_DESIGNATED_INITIALIZER;
/// 设置蓝牙服务UUID
- (void)setEuiccBleServiceUUIDWithServiceUUID:(NSString * _Nonnull)serviceUUID rxUUID:(NSString * _Nonnull)rxUUID txUUID:(NSString * _Nonnull)txUUID;
/// 连接设备
- (void)reopen;
/// 关闭设备连接
- (void)close;
/// 获取设备信息
- (GrpcDeviceInfo * _Nullable)getDeviceInfo SWIFT_WARN_UNUSED_RESULT;
/// 设置接收蓝牙数据时的延时
- (void)setDataDelaySecondWithDelaySecond:(double)delaySecond;
/// 设置发送蓝牙数据时的延时
- (void)setSendDataDelaySecondWithDelaySecond:(double)delaySecond;
- (void)requestWithType:(NSInteger)type data:(NSData * _Nonnull)data callback:(void (^ _Nonnull)(NSInteger, NSInteger, NSData * _Nullable))callback;
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
- (void)centralManager:(CBCentralManager * _Nonnull)central didConnectPeripheral:(CBPeripheral * _Nonnull)peripheral;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central didFailToConnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForDescriptor:(CBDescriptor * _Nonnull)descriptor error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForDescriptor:(CBDescriptor * _Nonnull)descriptor error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheralIsReadyToSendWriteWithoutResponse:(CBPeripheral * _Nonnull)peripheral;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didModifyServices:(NSArray<CBService *> * _Nonnull)invalidatedServices;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverDescriptorsForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK19EuiccGattAttributes")
@interface EuiccGattAttributes : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull EUICC_SERVICE;)
+ (NSString * _Nonnull)EUICC_SERVICE SWIFT_WARN_UNUSED_RESULT;
+ (void)setEUICC_SERVICE:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EUICC_SERVICE_32BIT_FRONT;)
+ (NSString * _Nonnull)EUICC_SERVICE_32BIT_FRONT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EUICC_SERVICE_32BIT;)
+ (NSString * _Nonnull)EUICC_SERVICE_32BIT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull RX;)
+ (NSString * _Nonnull)RX SWIFT_WARN_UNUSED_RESULT;
+ (void)setRX:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull TX;)
+ (NSString * _Nonnull)TX SWIFT_WARN_UNUSED_RESULT;
+ (void)setTX:(NSString * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class GCDAsyncSocket;
SWIFT_CLASS("_TtC14eSIMManagerSDK15EuiccWifiDevice")
@interface EuiccWifiDevice : AbstractPbDevice <GCDAsyncSocketDelegate>
@property (nonatomic, strong) LPAdDevice * _Nullable currentDevice;
/// 设备连接状态变化
@property (nonatomic, copy) void (^ _Nullable connectStateCallback)(enum DeviceConnectionState);
- (nonnull instancetype)initWithDevice:(LPAdDevice * _Nullable)device OBJC_DESIGNATED_INITIALIZER;
- (void)requestWithType:(NSInteger)type data:(NSData * _Nonnull)data callback:(void (^ _Nonnull)(NSInteger, NSInteger, NSData * _Nullable))callback;
- (void)reopen;
- (void)close;
- (void)socket:(GCDAsyncSocket * _Nonnull)sock didConnectToHost:(NSString * _Nonnull)host port:(uint16_t)port;
- (void)socketDidDisconnect:(GCDAsyncSocket * _Nonnull)sock withError:(NSError * _Nullable)err;
- (void)socket:(GCDAsyncSocket * _Nonnull)sock didWriteDataWithTag:(NSInteger)tag;
- (void)socket:(GCDAsyncSocket * _Nonnull)sock didReadData:(NSData * _Nonnull)data withTag:(NSInteger)tag;
- (NSTimeInterval)socket:(GCDAsyncSocket * _Nonnull)sock shouldTimeoutReadWithTag:(NSInteger)tag elapsed:(NSTimeInterval)elapsed bytesDone:(NSUInteger)length SWIFT_WARN_UNUSED_RESULT;
- (NSTimeInterval)socket:(GCDAsyncSocket * _Nonnull)sock shouldTimeoutWriteWithTag:(NSInteger)tag elapsed:(NSTimeInterval)elapsed bytesDone:(NSUInteger)length SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK11GrpcAPNInfo")
@interface GrpcAPNInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull apn;
@property (nonatomic, copy) NSString * _Nonnull userName;
@property (nonatomic, copy) NSString * _Nonnull userPass;
@property (nonatomic, copy) NSString * _Nonnull authType;
@property (nonatomic, copy) NSString * _Nonnull dialNum;
@property (nonatomic, copy) NSString * _Nonnull netType;
@property (nonatomic, copy) NSString * _Nonnull pdpType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK21GrpcCarrierIdentifier")
@interface GrpcCarrierIdentifier : NSObject
@property (nonatomic, copy) NSString * _Nonnull mcc;
@property (nonatomic, copy) NSString * _Nonnull mnc;
@property (nonatomic, copy) NSString * _Nonnull spn;
@property (nonatomic, copy) NSString * _Nonnull imsi;
@property (nonatomic, copy) NSString * _Nonnull gid1;
@property (nonatomic, copy) NSString * _Nonnull gid2;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, GrpcDeviceExtendAbility, open) {
  GrpcDeviceExtendAbilitySetApn = 0,
  GrpcDeviceExtendAbilityGetApn = 1,
  GrpcDeviceExtendAbilityEnableMobileData = 2,
  GrpcDeviceExtendAbilityEnableDataRoaming = 3,
  GrpcDeviceExtendAbilityEnableWifiConnect = 4,
  GrpcDeviceExtendAbilityCheckWifiConnect = 5,
  GrpcDeviceExtendAbilitySecureCommunication = 6,
  GrpcDeviceExtendAbilitySecurePsk = 7,
};

SWIFT_CLASS("_TtC14eSIMManagerSDK14GrpcDeviceInfo")
@interface GrpcDeviceInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull vendor;
@property (nonatomic, copy) NSString * _Nonnull imei;
@property (nonatomic, copy) NSString * _Nonnull sn;
@property (nonatomic, copy) NSString * _Nonnull deviceName;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull capability;
@property (nonatomic) BOOL scardMode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK20GrpcEuiccProfileInfo")
@interface GrpcEuiccProfileInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull iccid;
@property (nonatomic) int32_t state;
@property (nonatomic) int32_t policyRules;
@property (nonatomic, copy) NSString * _Nonnull nickname;
@property (nonatomic, copy) NSString * _Nonnull serviceProviderName;
@property (nonatomic, copy) NSString * _Nonnull profileName;
@property (nonatomic, strong) GrpcCarrierIdentifier * _Nullable carrierIdentifier;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK24GrpcEuiccProfileInfoList")
@interface GrpcEuiccProfileInfoList : NSObject
@property (nonatomic, copy) NSArray<GrpcEuiccProfileInfo *> * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK19GrpcEuiccServiceRsp")
@interface GrpcEuiccServiceRsp : NSObject
@property (nonatomic) int32_t result;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull activationCode;
@property (nonatomic, copy) NSString * _Nonnull eid;
@property (nonatomic, strong) GrpcEuiccProfileInfoList * _Nonnull profiles;
@property (nonatomic, copy) NSString * _Nonnull euiccInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK15GrpcWifiSetting")
@interface GrpcWifiSetting : NSObject
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP14eSIMManagerSDK13IDeviceExtend_")
@protocol IDeviceExtend
- (BOOL)hasAbility:(enum GrpcDeviceExtendAbility)ability SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setAPNWithApn:(GrpcAPNInfo * _Nonnull)apn error:(NSError * _Nullable * _Nullable)error;
- (GrpcAPNInfo * _Nullable)getAPNAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)enableMobileDataWithEnable:(BOOL)enable error:(NSError * _Nullable * _Nullable)error;
- (BOOL)enableDataRoamingWithEnable:(BOOL)enable error:(NSError * _Nullable * _Nullable)error;
- (BOOL)enableWifiConnectWithEnable:(BOOL)enable wifi:(GrpcWifiSetting * _Nonnull)wifi error:(NSError * _Nullable * _Nullable)error;
- (NSObject * _Nullable)checkWifiConnectAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK12LFCommonUtil")
@interface LFCommonUtil : NSObject
+ (BOOL)isHaveLFBleServiceWithAdvertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getBleDeviceMacAdressWithAdvertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)bleUuidStr128WithDeviceMac:(NSString * _Nonnull)deviceMac SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, LPAClientMode, open) {
  LPAClientModeJava = 1,
  LPAClientModeNative = 2,
};

SWIFT_CLASS("_TtC14eSIMManagerSDK10LPAdClient")
@interface LPAdClient : AbstractPbDevice
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSString *, LPAdClient *> * _Nonnull clients;)
+ (NSDictionary<NSString *, LPAdClient *> * _Nonnull)clients SWIFT_WARN_UNUSED_RESULT;
+ (void)setClients:(NSDictionary<NSString *, LPAdClient *> * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LPAdClient * _Nonnull shared;)
+ (LPAdClient * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) id <IDeviceExtend> _Nullable deviceExtend;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)createClientWithImei:(NSString * _Nonnull)imei nativeIdentity:(NSString * _Nonnull)nativeIdentity info:(GrpcDeviceInfo * _Nonnull)info pbDevice:(AbstractPbDevice * _Nonnull)pbDevice;
+ (NSString * _Nullable)createClientWithSlotId:(NSInteger)slotId imei:(NSString * _Nonnull)imei nativeIdentity:(NSString * _Nonnull)nativeIdentity info:(GrpcDeviceInfo * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
+ (LPAdClient * _Nullable)getClientWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (void)closeNativeClient;
+ (void)removeAllClient;
+ (void)removeClientWithId:(NSString * _Nonnull)identity;
+ (void)setCreateClientModeWithMode:(enum LPAClientMode)mode;
+ (void)deleteSecurityData:(NSString * _Nonnull)identity slotId:(NSInteger)slotId;
- (AbstractPbDevice * _Nullable)getDevice SWIFT_WARN_UNUSED_RESULT;
- (void)reopen;
- (void)close;
- (NSString * _Nullable)getDeviceId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)onGetEid SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)onGetEuiccInfo SWIFT_WARN_UNUSED_RESULT;
- (GrpcEuiccServiceRsp * _Nonnull)onGetEuiccProfileInfoList SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)onSwitchToSubscriptionWithIccid:(NSString * _Nonnull)iccid SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)onUpdateSubscriptionNicknameWithIccid:(NSString * _Nonnull)iccid nickname:(NSString * _Nonnull)nickname SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)onDeleteSubscriptionWithIccid:(NSString * _Nonnull)iccid SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)onDownloadSubscriptionWithActivationCode:(NSString * _Nonnull)activationCode confirmationCode:(NSString * _Nonnull)confirmationCode SWIFT_WARN_UNUSED_RESULT;
- (DownloadMetadataResult * _Nonnull)onGetDownloadableSubscriptionMetadataWithActivationCode:(NSString * _Nonnull)activationCode SWIFT_WARN_UNUSED_RESULT;
- (DSListResult * _Nonnull)onGetDefaultDownloadableSubscriptionList SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)onDisableSubscriptionWithIccid:(NSString * _Nonnull)iccid SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)setDefaultSmdpAddressWithAddress:(NSString * _Nonnull)address SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDefaultSmdpAddress SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)setSmdsAddressWithAddress:(NSString * _Nonnull)address SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getSmdsAddress SWIFT_WARN_UNUSED_RESULT;
- (void)requestWithType:(NSInteger)type data:(NSData * _Nonnull)data callback:(void (^ _Nonnull)(NSInteger, NSInteger, NSData * _Nullable))callback;
- (BOOL)isSCardMode SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)extendChangeSecurePSKWithPsk:(NSString * _Nonnull)psk SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)extendSetSecureCommunicationWithCode:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)syncNotifications SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserAuthenticationCallbackWithCallback:(NSString * _Nullable (^ _Nonnull)(void))callback;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK14PbDeviceExtend")
@interface PbDeviceExtend : NSObject <IDeviceExtend>
- (BOOL)hasAbility:(enum GrpcDeviceExtendAbility)ability SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setAPNWithApn:(GrpcAPNInfo * _Nonnull)apn error:(NSError * _Nullable * _Nullable)error;
- (GrpcAPNInfo * _Nullable)getAPNAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)enableMobileDataWithEnable:(BOOL)enable error:(NSError * _Nullable * _Nullable)error;
- (BOOL)enableDataRoamingWithEnable:(BOOL)enable error:(NSError * _Nullable * _Nullable)error;
- (BOOL)enableWifiConnectWithEnable:(BOOL)enable wifi:(GrpcWifiSetting * _Nonnull)wifi error:(NSError * _Nullable * _Nullable)error;
- (NSObject * _Nullable)checkWifiConnectAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK17SecurityBleDevice")
@interface SecurityBleDevice : EuiccBleDevice
- (nonnull instancetype)initWithIdentity:(NSString * _Nonnull)identity bleManager:(CBCentralManager * _Nonnull)bleManager blePeripheral:(CBPeripheral * _Nonnull)blePeripheral slotId:(NSInteger)slotId bleDataLengthSize:(NSInteger)bleDataLengthSize OBJC_DESIGNATED_INITIALIZER;
- (GrpcDeviceInfo * _Nullable)getDeviceInfo SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithBleManager:(CBCentralManager * _Nonnull)bleManager blePeripheral:(CBPeripheral * _Nonnull)blePeripheral bleDataLengthSize:(NSInteger)bleDataLengthSize SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK17eSIMManagerConfig")
@interface eSIMManagerConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger bleDataLengthSize;)
+ (NSInteger)bleDataLengthSize SWIFT_WARN_UNUSED_RESULT;
+ (void)setBleDataLengthSize:(NSInteger)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14eSIMManagerSDK16eSIMManagerConst")
@interface eSIMManagerConst : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint16_t kDefaultSocketPort;)
+ (uint16_t)kDefaultSocketPort SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull KEY_EUICC_API_TIMEOUT;)
+ (NSString * _Nonnull)KEY_EUICC_API_TIMEOUT SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
